## NUMPY ARRAY AND BASICS

In [3]:
from numpy import *

CREATIONG ARRAY FROM LIST


In [5]:
arr_1d=array([1, 2, 3, 4, 5])
print("arr_1d:", arr_1d)

arr_2d=array([[1, 2, 3], [4, 5, 6]])
print("arr_2d:", arr_2d)



arr_1d: [1 2 3 4 5]
arr_2d: [[1 2 3]
 [4 5 6]]


LIST VS NUMPY ARRAY

In [8]:
py_list=[1, 2, 3, 4, 5]
print("py_list:",py_list*2) # here list is repeated 2 times, not multiplied by 2 because list is not a numpy array

np_array=array([1, 2, 3, 4, 5])
print("np_array:",np_array*2) # here array is multiplied by 2, not repeated 2 times

import time
start=time.time() # HERE CALCULATING LIST OPERATION TIME
py_list=[i*2 for i in range(1000)] # MEANS MULTIPLYING EACH ELEMENT OF LIST BY 2
print("\n list op time : ",time.time()-start) # MEANS 

start=time.time()
np_array=arange(1000)*2   # THIS IS MUCH FASTER THAN LIST COMPREHENSION BECAUSE NUMPY USES C-LANGUAGE FOR ITS OPERATIONS
print("\n NUMPY op time : ",time.time()-start)

py_list: [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
np_array: [ 2  4  6  8 10]

 list op time :  0.0020401477813720703

 NUMPY op time :  0.0013413429260253906


CREATING ARRAY FROM SCRATCH

In [28]:
zeros_array=np.zeros((2, 3)) # CREATING 2D ARRAY OF ZEROS
print("\n zeros_array : \n",zeros_array)

ones_array=np.ones((2, 3)) # CREATING 2D ARRAY OF ONES
print("\n ones_array : \n",ones_array)

full=np.full((2, 3), 7) # CREATING 2D ARRAY OF 7s
print("\n full : \n",full)

random=np.random.random((2, 3)) # CREATING 2D ARRAY OF RANDOM NUMBERS
print("\n random array : \n",random)

sequence = np.arange(0, 10, 2) # CREATING 1D ARRAY OF SEQUENCE OF NUMBERS FROM 0 TO 10 WITH STEP SIZE OF 2
print("\n sequence : \n",sequence)


 zeros_array : 
 [[0. 0. 0.]
 [0. 0. 0.]]

 ones_array : 
 [[1. 1. 1.]
 [1. 1. 1.]]

 full : 
 [[7 7 7]
 [7 7 7]]

 random array : 
 [[0.29639449 0.44187977 0.46871864]
 [0.70775107 0.87699644 0.96252084]]

 sequence : 
 [0 2 4 6 8]


VECTOR , MATRIX , TENSOR

In [ ]:
vector = np.array([1, 2, 3]) # CREATING 1D ARRAY OF VECTOR
print("\n vector : \n",vector)

matrix=np.array([[1, 2, 3], 
                [4, 5, 6]]) # CREATING 2D ARRAY OF MATRIX
print("\n matrix : \n",matrix)

tensor=np.array([[[1, 2], [3, 4]],
                [[5, 6], [7, 8]]]) # CREATING 3D ARRAY OF TENSOR
print("\n tensor : \n",tensor)




 vector : 
 [1 2 3]

 matrix : 
 [[1 2 3]
 [4 5 6]]

 tensor : 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


ARRAY PROPERTIES

In [32]:
arr=np.array([[1, 2, 3], 
            [4, 5, 6]])
print("shape: ",arr.shape) # PRINTING SHAPE OF ARRAY
print("dimensions: ",arr.ndim) # PRINTING NUMBER OF DIMENSIONS OF ARRAY
print("size: ",arr.size) # PRINTING TOTAL NUMBER OF ELEMENTS IN ARRAY
print("data type: ",arr.dtype) # PRINTING DATA TYPE OF ARRAY

shape:  (2, 3)
dimensions:  2
size:  6
data type:  int64


ARRAY RESHAPING

In [40]:
arr = np.arange(10) # CREATING 1D ARRAY OF NUMBERS FROM 0 TO 9
print("\n arr : ",arr)

reshaped=arr.reshape(5, 2) # RESHAPING 1D ARRAY TO 2D ARRAY OF SHAPE (5, 2)
print("\n reshaped : \n",reshaped)

flattened=reshaped.flatten() # FLATTENING 2D ARRAY TO 1D ARRAY
print("\n flattened : \n",flattened) #copy of array is created, so if we change the original array, the flattened array will not change 

ravelled=reshaped.ravel() # RAVELING 2D ARRAY TO 1D ARRAY
print("\n ravelled : \n",ravelled) #means copy of array is not created, it is just a view of original array, so if we change the original array, the ravelled array will also change

#TRANSPOSE OF ARRAY
transposed=reshaped.T # TRANSPOSE OF 2D ARRAY
print("\n transposed : \n",transposed)


 arr :  [0 1 2 3 4 5 6 7 8 9]

 reshaped : 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

 flattened : 
 [0 1 2 3 4 5 6 7 8 9]

 ravelled : 
 [0 1 2 3 4 5 6 7 8 9]

 transposed : 
 [[0 2 4 6 8]
 [1 3 5 7 9]]
