## Numpy ARRAY OPERATIONS

In [5]:
import numpy as np

In [9]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print("basic slicing: ",arr[2:7])
print("slicing with step: ",arr[1:10:2])
print("slicing with negative step: ",arr[-3])

basic slicing:  [3 4 5 6 7]
slicing with step:  [ 2  4  6  8 10]
slicing with negative step:  8


In [12]:
arr_2d=np.array([[1,2,3], # 0 
                 [4,5,6],  #1
                 [7,8,9]]) # 2
print("specific array element: ",arr_2d[1,2]) #means row 1 and column 2
print("entire row: ",arr_2d[1]) #means row 1 and all columns
print("entire column: ",arr_2d[:,2]) #means all rows and column 2


specific array element:  6
entire row:  [4 5 6]
entire column:  [3 6 9]


SHORTING


In [28]:
unshorted_arr=np.array([3,1,2,5,4,6,8,7,9])
print("unshorted array: ",np.sort(unshorted_arr))

arr_2d_unsorted=np.array([[3,1],[6,2],[5,4]])
print("unsorted 2D array column-wise: ",np.sort(arr_2d_unsorted,axis=0)) #sorts each column 
# axis=0 means sort along the rows, i.e. sort each column



unshorted array:  [1 2 3 4 5 6 7 8 9]
unsorted 2D array column-wise:  [[3 1]
 [5 2]
 [6 4]]


FILTRING
##

In [29]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
evennumbers = numbers[numbers % 2 == 0] #expression evaluates to True for even numbers and False for odd numbers, so we can use it to filter the array and get only the even numbers.
print("Even numbers: ", evennumbers)

Even numbers:  [ 2  4  6  8 10]


FILTER WITH MASK

In [30]:
mask = numbers>5
print("numbers greater than 5: ", numbers[mask]) #filtering the array using the mask

numbers greater than 5:  [ 6  7  8  9 10]


FANCY INDEXING VS  np.where()

In [32]:
indices = [0, 2, 4, 6, 8]
print("elements at specific indices: ", numbers[indices]) #filtering the array using a list of indices

where_result = np.where(numbers > 5)
print(where_result) #returns the indices of the elements that satisfy the condition
print("elements at specific indices using np.where: ", numbers[where_result]) #filtering the array using the indices returned by np.where



elements at specific indices:  [1 3 5 7 9]
(array([5, 6, 7, 8, 9]),)
elements at specific indices using np.where:  [ 6  7  8  9 10]


In [34]:
condition_array = np.where(numbers > 5,numbers*2,numbers)
print("condition array: ", condition_array) #returns a tuple of arrays, one for each dimension of the input array, containing the indices of the elements that satisfy the condition



condition array:  [ 1  2  3  4  5 12 14 16 18 20]


In [36]:
condition_array1 = np.where(numbers > 5,"true","false")
print("condition array: ", condition_array1) #returns a tuple of arrays, one for each dimension of the input array, containing the indices of the elements that satisfy the condition



condition array:  ['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


ADD AND REMOVE DATA


In [ ]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

addition = arr1 + arr2  # op = [5, 7, 9]
print("combined array: ", addition) #returns a tuple of arrays, one for each dimension

# marged arrays  concatenate
combined = np.concatenate((arr1, arr2))  # op = [1, 2, 3, 4, 5, 6]
print("combined array: ", combined) #returns a tuple of arrays, one for each dimension


combined array:  [5 7 9]
combined array:  [1 2 3 4 5 6]


## ARRAY COMPATIBILITY

In [40]:
a= np.array([1,2,3])
b= np.array([4,5,6,7])
c=np.array([7,8,9])

print("COMPATIBILITY SHAPES: ",a.shape==b.shape)

COMPATIBILITY SHAPES:  False


In [44]:
original = np.array([[1, 2], [3, 4]])
new_row = np.array([[5, 6]])

with_new_row = np.vstack((original, new_row))
print(original)
print("\n", with_new_row)

new_col = np.array([[7], [8]])
with_new_col = np.hstack((original, new_col))
print("\n",original)
print("\n", with_new_col)

[[1 2]
 [3 4]]

 [[1 2]
 [3 4]
 [5 6]]

 [[1 2]
 [3 4]]

 [[1 2 7]
 [3 4 8]]


DELETE

In [49]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
deleted = np.delete(arr,2)
print("original array: ", arr)
print("array after deleting element at index 2: ", deleted)

arr1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
deleted_item = np.delete(arr1[1], 1)
print("original array:\n", arr1)
print("array after deleting element at index 1 from row 1:\n", deleted_item)

original array:  [ 1  2  3  4  5  6  7  8  9 10]
array after deleting element at index 2:  [ 1  2  4  5  6  7  8  9 10]
original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array after deleting element at index 1 from row 1:
 [4 6]
